swagger: "2.0"
info:
  description: "Nicolas Coen"
  version: "1.0.0"
  title: "TP API REST"
  contact:
    email: "ncoen97@gmail.com"
host: "localhost:8080"
basePath: "/"
tags:
- name: "cursos"
  description: "Todos sobre los cursos"
- name: "users"
  description: "Operations about user"
schemes:
- "http"
paths:
  /:
    get:
      tags:
      - "cursos"
      summary: "Pagina de inicio"
      description: ""
      operationId: "inicio"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      security:
        - Bearer: []
      responses:
        200:
          description: "Exitoso"
        500:
          description: "Ocurrió un error con un módulo interno"
  /cursos:
    get:
      tags:
      - "cursos"
      summary: "Obtener todos los cursos"
      description: ""
      operationId: "getcursos"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "anio_de_dictado"
        in: "query"
        description: "Para filtrar por año de dictado del curso"
        type: "integer"
      - name: "duracion"
        in: "query"
        description: "Para filtrar por la duracion del curso"
        type: "integer"
      security:
        - Bearer: []
      responses:
        200:
          description: "Exitoso"
        500:
          description: "Ocurrió un error con un módulo interno"
    post:
      tags:
      - "cursos"
      summary: "Agregar un curso"
      description: ""
      operationId: "postcurso"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      security:
        - Bearer: []
      parameters:
      - in: "body"
        name: "body"
        description: "Curso a agregar"
        required: true
        schema:
          $ref: "#/definitions/Curso"
      responses:
        400:
          description: "Error en los parametros"
        201:
          description: "Curso agregado con exito"
        500:
          description: "Ocurrió un error con un módulo interno"
  /cursos/:id:
    get:
      tags:
      - "cursos"
      summary: "Obtener un curso por id"
      description: "Para obtener un id valido puede consultar por los cursos con GET /cursos"
      operationId: "getcursoid"
      produces:
      - "application/json"
      security:
        - Bearer: []
      responses:
        404:
          description: "El recurso no fue encontrado"
        200:
          description: "Exito"
        500:
          description: "Ocurrió un error con un módulo interno"
    delete:
      tags:
      - "cursos"
      summary: "Eliminar un curso por id"
      description: "Para obtener un id valido puede consultar por los cursos con GET /cursos"
      operationId: "deletecursoid"
      produces:
      - "application/json"
      security:
        - Bearer: []
      responses:
        200:
          description: "Exito"
        500:
          description: "Ocurrió un error con un módulo interno"
  /cursos/:id/alumnos:
    get:
      tags:
      - "cursos"
      summary: "Obtener los alumnos de un curso"
      description: "Devuelve el array de alumnos"
      operationId: "getcursosidalumnos"
      produces:
      - "application/json"
      security:
        - Bearer: []
      responses:
        200:
          description: "Exito"
        404:
          description: "Recurso no encontrado"
        500:
          description: "Ocurrió un error con un módulo interno"
  /cursos/:id/alumnoDestacado:
    get:
      tags:
      - "cursos"
      summary: "Obtener el alumno destacado de un curso"
      description: "Devuelve el alumno"
      operationId: "getcursosidalumnodestacado"
      produces:
      - "application/json"
      responses:
        200:
          description: "Exito"
        404:
          description: "Recurso no encontrado"
        500:
          description: "Ocurrió un error con un módulo interno"
      security:
        - Bearer: []
  /users:
    post:
      tags:
      - "users"
      summary: "Registro de usuarios"
      description: ""
      operationId: "users"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Nuevo usuario"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        201:
          description: "Usuario creado"
        500:
          description: "Ocurrió un error con un módulo interno"
  /users/login:
    post:
      tags:
      - "users"
      summary: "Logeo a la api, devuelve el token para consultar"
      description: ""
      operationId: "userslogin"
      produces:
      - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Nuevo usuario"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        '200':
          description: "Usuario creado"
          schema: 
            $ref: '#/definitions/Auth'
        401:
          description: "Error en la autenticacion"
securityDefinitions:
  Bearer:
    type: apiKey
    name: authorization
    in: header
definitions:
  Curso:
    type: "object"
    properties:
      anio_de_dictado: 
        type: "integer"
      duracion: 
        type: "integer"
      tema: 
        type: "string"
      alumno:
        type: "array"
        items:
          $ref: "#/definitions/Cliente"
    xml:
      name: "Curso"
  Cliente:
    type: "object"
    properties:
      nombre:
        type: "string"
      apellido:
        type: "string"
      DNI:
        type: "integer"
      direccion:
        type: "string"
      nota:
        type: "integer"
    xml:
      name: "Cliente"
  User:
    type: "object"
    properties:
      username:
        type: "string"
      password:
        type: "string"
    xml:
      name: "User"
  Auth:
    type: "object"
    properties:
      token:
        type: "string"
      expiresIn: 
        type: "integer"
      msg: 
        type: "string"
    xml:
      name: "Auth"